default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER', 'mysql2') %>
  encoding: utf8
  support_json: <%= ENV.fetch('DATABASE_SUPPORT_JSON', 'true') %>
  collation: <%= ENV.fetch('DATABASE_COLLATION', 'utf8_general_ci') %>
  pool: <%= ENV.fetch("RAILS_MAX_DB_THREADS", 8).to_i * ENV.fetch("WEB_CONCURRENCY", 1).to_i %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 3306) %>
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('DATABASE_PASS', 'password') %>

development:
  <<: *default
  database: rookie_development

test:
  <<: *default
  database: rookie_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'rookie_production') %>
